### ISSUE TITLE
Coordinates doesn't seem to work when files have commas in names

### ISSUE THREAD

**Issue by oyvindsolstad** [valentine195/obsidian-leaflet-plugin#134]
Hi, 

I name US cities as this: `[[City name, State abbreviation]]`

Example: `[[New Orleans, LA]]`

This seem to cause problems for the **coordinates** function. When using New Orleans (or any other place where the city has a comma in the name/file name), the map doesn't center on the wanted city.

**Comment by oyvindsolstad** [comment]
Code with no comma in coordinates function:

![Skjermbilde 2021-06-22 kl  12 16 02](https://user-images.githubusercontent.com/4631971/122907693-b194d700-d353-11eb-893b-29f80c963cbb.png)

Result:

![Skjermbilde 2021-06-22 kl  12 15 59](https://user-images.githubusercontent.com/4631971/122907766-c3767a00-d353-11eb-98a2-ea9754708de8.png)

---

Code with comma in coordinates function:

![Skjermbilde 2021-06-22 kl  12 16 15](https://user-images.githubusercontent.com/4631971/122907819-ccffe200-d353-11eb-81c7-020b0e14fbb8.png)

Result:

![Skjermbilde 2021-06-22 kl  12 16 18](https://user-images.githubusercontent.com/4631971/122907848-d2f5c300-d353-11eb-801c-ebb1993ada2f.png)

**Comment by Moonbase59** [comment]
Hmm. This would be because the code block is now parsed as YAML, I think. The comma would make up a new array element.

**Comment by oyvindsolstad** [comment]
Nope, same result.

**Comment by Moonbase59** [comment]
Looks like a bug. It works for

```yaml
markerFile: "[[Elvenking’s Halls, Test]]"
```

here, but not for

```yaml
coordinates: "[[Location, current]]"
```

Console log:

```text
app.js:1 Uncaught (in promise) TypeError: Cannot read property 'extension' of null
    at t.fileToLinktext (app.js:1)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:24802:56)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:30:58)
t.fileToLinktext @ app.js:1
eval @ utils.ts:446
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
eval @ utils.ts:218
eval @ utils.ts:218
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
getImmutableItems @ utils.ts:197
eval @ main.ts:246
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
postprocessor @ main.ts:130
(anonymous) @ app.js:1
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Be @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.openFile @ app.js:1
t.onFileClick @ app.js:1
s @ app.js:1
```

**Comment by Moonbase59** [comment]
Just for finding things out, could you try

```yaml
coordinates: [["New Orleans, LA"]]
```

(I know this is awkward, and Obsidian suggest will complain "No file found". Just for a quick check.)

**Comment by oyvindsolstad** [comment]
That works.

**Comment by Moonbase59** [comment]
Well, this is just a quick-n-dirty workaround. It’s really not easy bringing those wikilinks and YAML syntax under one hat … Let’s see what @valentine195 comes up with.

**Comment by valentine195** [comment]
Closed in 3.19.0

**Comment by Moonbase59** [comment]
Hm. Using

```yaml
markerFile: [[Berlin, Weltzeituhr]]
```

didn’t work with 3.19.0.

**Comment by Moonbase59** [comment]
Probably also better check for

```yaml
linksFrom:
linksTo:
```

**Comment by valentine195** [comment]
These should all be fixed by the YAML parsing update, but my guess is the plugin doesn't like them because it isn't removing the brackets now. Should be a quick fix once I get a chance.

**Comment by oyvindsolstad** [comment]
```
There was an error rendering the map:

linksFrom.flat is not a function
```

The code generating this is a linksFrom: [[city, state]] file

**Comment by valentine195** [comment]
The rest of the parameters should now also parse correctly in 3.19.1

**Comment by Moonbase59** [comment]
Confirmed working in 3.19.1 for:

```yaml
markerFile:
linksFrom:
linksTo:
```

**Comment by Moonbase59** [comment]
@oyvindsolstad: Can you confirm it works now with 3.19.1? If yes, let’s close this.

**Comment by oyvindsolstad** [comment]
It works!

Thank you, @valentine195

**Comment by oyvindsolstad** [comment]
Works now!
