### ISSUE TITLE
3.19.0: Previously working map shows "geojson.flat" error

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#148]
Map working in 3.18.4 now shows error using 3.19.0:

````
```leaflet
id: Main Map
markerFolder: People
markerFolder: Locations
markerFolder: Events
#markerFolder: -Inbox
#markerFile: [[Matthias C. Hormann]]
#markerTag: family
#linksFrom: [[-Friends & Family TOC]]
height: 500px
lat: 51.133333
long: 10.416667
minZoom: 1
maxZoom: 18
defaultZoom: 5.5
zoomDelta: 0.5
unit: km
distanceMultiplier: 1.3
#marker: Check, 48.23875, 10.37595, [[Matthias C. Hormann]]
#overlay: [[green, [48.23875, 10.37595], 50 km, "Test from code block"]]
overlayTag: nearby
overlayColor: 'rgba(218, 165, 32, .6)'
geojson: [[geo-germany-bundesländer.geojson]]
#geojsonColor: '#0000fe'
```
````

```text
main.ts:669 TypeError: geojson.flat is not a function or its return value is not iterable
    at ObsidianLeaflet.eval (eval at <anonymous> (app.js:1), <anonymous>:31906:46)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:33:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:29:12)
    at ObsidianLeaflet.postprocessor (eval at <anonymous> (app.js:1), <anonymous>:31877:16)
    at app.js:1
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
eval @ main.ts:669
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
postprocessor @ main.ts:131
(anonymous) @ app.js:1
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Be @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.openFile @ app.js:1
t.onFileClick @ app.js:1
s @ app.js:1
```

**Comment by valentine195** [comment]
Thanks missed this in my YAML parsing update. For now if you need it to work, making the geojson an array should fix it.

**Comment by Moonbase59** [comment]
Confirmed

**Comment by valentine195** [comment]
Should be fixed in 3.19.1

**Comment by Moonbase59** [comment]
Confirm fixed in 3.19.1.
